# version: '3.3'

services:

  nginx:
      build:
        context: ./requirements/nginx/
      entrypoint:
        - nginx
        - -g
        - "daemon off;" 
        # - tail 
        # - -f 
        # - /var/log/nginx/error.log

      volumes:
        - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      ports:
      - "443:443"
      # restart: always
      # network:
      # depends_on: