# Utilise l'image officielle de WordPress
FROM wordpress:latest

# Ajoutez des plugins ou des personnalisations ici si nécessaire
# COPY mon_plugin /var/www/html/wp-content/plugins/

# Expose le port 9000 pour PHP-FPM
EXPOSE 9000
