# Utilise l'image officielle de MySQL
FROM mysql:latest

# Spécifiez la configuration de la base de données si nécessaire
# COPY mon_fichier_de_configuration.cnf /etc/mysql/conf.d/

# Expose le port 3306 pour la base de données
EXPOSE 3306